WITH TBL AS (
  SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
  FROM ONLINE_SALE
  WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
  
  UNION ALL

  SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
  FROM OFFLINE_SALE
  WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202203'
)

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d'), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM TBL
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID