-- 코드를 입력하세요
SELECT MEMBER_ID m, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH from MEMBER_PROFILE where  MONTH(DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL AND GENDER='W' order by MEMBER_ID

# select * from MEMBER_PROFILE