
-- 각 분화된 연도별 가장 큰 대장균 크기 구하기 
# SELECT YEAR(DIFFERENTIATION_DATE) AS group_year, MAX(SIZE_OF_COLONY) AS max_size
# FROM ECOLI_DATA ed
# GROUP BY YEAR(DIFFERENTIATION_DATE)

-- 편차 구하기 
SELECT YEAR(ed.DIFFERENTIATION_DATE) AS YEAR, edmy.max_size - ed.SIZE_OF_COLONY AS YEAR_DEV,  ed.ID
FROM ECOLI_DATA ed 
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS group_year, MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA ed
    GROUP BY YEAR(DIFFERENTIATION_DATE)) edmy
ON edmy.group_year = YEAR(ed.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
