SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
JOIN (
  SELECT FISH_TYPE, MAX(LENGTH) AS ML
  FROM FISH_INFO
  WHERE LENGTH IS NOT NULL
  GROUP BY FISH_TYPE
) tm ON fi.FISH_TYPE = tm.FISH_TYPE AND fi.LENGTH = tm.ML
ORDER BY fi.ID;